<template>
  <div class="loadingio-spinner-spinner-iu20vjndzof">
    <div class="ldio-w67b24x62o">
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
      <div></div>
    </div>
  </div>
</template>
<style lang="scss">
@keyframes ldio-w67b24x62o {
  0% {
    opacity: 1;
  }
  100% {
    opacity: 0;
  }
}
.ldio-w67b24x62o div {
  left: 191.9px;
  top: 96.96000000000001px;
  position: absolute;
  animation: ldio-w67b24x62o linear 1s infinite;
  background: #fe718d;
  width: 20.2px;
  height: 48.480000000000004px;
  border-radius: 10.1px / 24.240000000000002px;
  transform-origin: 10.1px 105.04px;
}
.ldio-w67b24x62o div:nth-child(1) {
  transform: rotate(0deg);
  animation-delay: -0.9166666666666666s;
  background: #fe718d;
}
.ldio-w67b24x62o div:nth-child(2) {
  transform: rotate(30deg);
  animation-delay: -0.8333333333333334s;
  background: #fe718d;
}
.ldio-w67b24x62o div:nth-child(3) {
  transform: rotate(60deg);
  animation-delay: -0.75s;
  background: #fe718d;
}
.ldio-w67b24x62o div:nth-child(4) {
  transform: rotate(90deg);
  animation-delay: -0.6666666666666666s;
  background: #fe718d;
}
.ldio-w67b24x62o div:nth-child(5) {
  transform: rotate(120deg);
  animation-delay: -0.5833333333333334s;
  background: #fe718d;
}
.ldio-w67b24x62o div:nth-child(6) {
  transform: rotate(150deg);
  animation-delay: -0.5s;
  background: #fe718d;
}
.ldio-w67b24x62o div:nth-child(7) {
  transform: rotate(180deg);
  animation-delay: -0.4166666666666667s;
  background: #fe718d;
}
.ldio-w67b24x62o div:nth-child(8) {
  transform: rotate(210deg);
  animation-delay: -0.3333333333333333s;
  background: #fe718d;
}
.ldio-w67b24x62o div:nth-child(9) {
  transform: rotate(240deg);
  animation-delay: -0.25s;
  background: #fe718d;
}
.ldio-w67b24x62o div:nth-child(10) {
  transform: rotate(270deg);
  animation-delay: -0.16666666666666666s;
  background: #fe718d;
}
.ldio-w67b24x62o div:nth-child(11) {
  transform: rotate(300deg);
  animation-delay: -0.08333333333333333s;
  background: #fe718d;
}
.ldio-w67b24x62o div:nth-child(12) {
  transform: rotate(330deg);
  animation-delay: 0s;
  background: #fe718d;
}
.loadingio-spinner-spinner-iu20vjndzof {
  width: 404px;
  height: 404px;
  display: inline-block;
  overflow: hidden;
  background: #ffffff;
}
.ldio-w67b24x62o {
  width: 100%;
  height: 100%;
  position: relative;
  transform: translateZ(0) scale(1);
  backface-visibility: hidden;
  transform-origin: 0 0; /* see note above */
}
.ldio-w67b24x62o div {
  box-sizing: content-box;
}
/* generated by https://loading.io/ */
</style>
